[build]
command = "npm run build:prod"
publish = "dist"

[context.production]
command = "npm run build:prod"
publish = "dist"

[context.deployment-preview]
command = "npm run build:prod"
publish = "dist"

[context.branch-deploy]
command = "npm run build:prod"
publish = "dist"

[dev]
command = "npm run dev"
port = 5173