[build]
command = "npm install --legacy-peer-deps && npm run build:prod"
publish = "dist"

[context.production]
command = "npm install --legacy-peer-deps && npm run build:prod"
publish = "dist"

[context.deployment-preview]
command = "npm install --legacy-peer-deps && npm run build:prod"
publish = "dist"

[context.branch-deploy]
command = "npm install --legacy-peer-deps && npm run build"
base = "/"
publish = "dist"

[dev]
command = "npm run dev"
port = 5173