[build]
  command = "npm install && npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"
  publish = "dist"

[context.deployment-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
  base = "/"

[dev]
  command = "npm run dev"
  port = 5173