[build]
  command = "npm run build:prod"
  publish = "dist"

[context.production]
  command = "npm run build:prod"
  publish = "dist"
  environment = {
    SUPABASE_URL = "${SUPABASE_URL}"
    SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
    WEATHER_API_KEY = "${WEATHER_API_KEY}"
    NODE_ENV = "production"
  }

[context.deployment-preview]
  command = "npm run build:prod"
  publish = "dist"
  environment = {
    SUPABASE_URL = "${SUPABASE_URL}"
    SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
    WEATHER_API_KEY = "${WEATHER_API_KEY}"
    NODE_ENV = "preview"
  }

[context.branch-deploy]
  command = "npm run build:prod"
  publish = "dist"
  environment = {
    SUPABASE_URL = "${SUPABASE_URL}"
    SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
    WEATHER_API_KEY = "${WEATHER_API_KEY}"
    NODE_ENV = "development"
  }

[dev]
  command = "npm run dev"
  port = 5173
  environment = {
    SUPABASE_URL = "${SUPABASE_URL}"
    SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
    WEATHER_API_KEY = "${WEATHER_API_KEY}"
    NODE_ENV = "development"
  }